var img;
var arrowL;
var arrowR;
var arrowU;
var arrowD;
var arrowT;
var arrowA;
var digit1;
var digit9;
function setup() {
    createCanvas(window.innerWidth, window.innerHeight);
    img = loadImage('https://i.imgur.com/x4d9oJq.jpeg');
    arrowL = loadImage('https://i.imgur.com/U6e4u8g.png');
    arrowA = loadImage('https://i.imgur.com/R3qhKSK.png');
    arrowD = loadImage('https://i.imgur.com/VHBYm2m.png');
    arrowR = loadImage('https://i.imgur.com/WEJqBW2.png');
    arrowT = loadImage('https://i.imgur.com/F8BkZHC.png');
    arrowU = loadImage('https://i.imgur.com/xNV0mL1.png');
    digit0 = loadImage('https://i.imgur.com/LeOOlXR.png');
    digit1 = loadImage('https://i.imgur.com/tRtBikl.png');
    digit2 = loadImage('https://i.imgur.com/ca86lC6.png');
    digit3 = loadImage('https://i.imgur.com/3nlbtVA.png');
    digit4 = loadImage('https://i.imgur.com/rJKukHL.png');
    digit5 = loadImage('https://i.imgur.com/kBXfgbj.png');
    digit6 = loadImage('https://i.imgur.com/kotOeBm.png');
    digit7 = loadImage('https://i.imgur.com/zPyxiJS.png');
    digit8 = loadImage('https://i.imgur.com/QZMVB9U.png');
    digit9 = loadImage('https://i.imgur.com/YlQtuEW.png');
    number0 = loadImage('https://i.imgur.com/c8AZ2DE.png');
    number1 = loadImage('https://i.imgur.com/Kw2Er2W.png');
    number2 = loadImage('https://i.imgur.com/XS4rMFc.png');
    number3 = loadImage('https://i.imgur.com/lq6bkh0.png');
    number4 = loadImage('https://i.imgur.com/C3HBKsV.png');
    number5 = loadImage('https://i.imgur.com/2QX16zE.png');
    number6 = loadImage('https://i.imgur.com/qL8UOyf.png');
    number7 = loadImage('https://i.imgur.com/Rk76ACs.png');
    number8 = loadImage('https://i.imgur.com/DPBQlto.png');
    number9 = loadImage('https://i.imgur.com/g5CBa3O.png');
    lessons = loadImage('https://i.imgur.com/6o5wazD.png');
    speedTest = loadImage('https://i.imgur.com/RUVyrSb.jpg');

}